### ISSUE TITLE
Разобраться можно ли не использовать React.StrictMode

### ISSUE THREAD

**Issue by karambirov** [StayInLight/react-weather-app#23]
> При использовании `StrictMode` запрос к сети делался дважды, я полагаю, что это как-то связано с `ServiceWorkers`, которые мы не используем в нашем проекте
_Originally posted by @StayInLight in https://github.com/StayInLight/react-weather-app/pull/21#discussion_r502927976_

По умолчанию этот режим включен, наверняка это не просто так. Сейчас его отключили, но нужно понять не выстрелит ли это нам в ногу в каких-то ситуациях.
Это не последний наш проект, поэтому это важно понимать

### Что нужно сделать?
- [x] Узнать можно ли не использовать `React.StrictMode` и на что он вообще влияет.
- [x] Результат исследования опубликовать в комментариях к этой задаче

**Comment by karambirov** [comment]
@StayInLight, сформулируй, что узнал и какое решение принято. Напиши здесь и закрой задачу)

**Comment by tirakhimov** [comment]
Выдержка из документации:

"StrictMode — инструмент для обнаружения потенциальных проблем в приложении. Также как и Fragment, StrictMode не рендерит видимого UI. Строгий режим активирует дополнительные проверки и предупреждения для своих потомков.

Примечание:

Проверки строгого режима работают только в режиме разработки; они не оказывают никакого эффекта в продакшен-сборке."

**В дальнейшем будет использоваться в проекте для обнаружения потенциальных проблем**
