### ISSUE TITLE
Сделать так, чтобы название вкладки браузера (title в head) отражало данные о локации и времени

### ISSUE THREAD

**Issue by tirakhimov** [StayInLight/react-weather-app#27]
### Что нужно сделать

Если пользователь вводит Санкт-Петербург, рендерится "Погода в Санкт-Петербурге", меняет в поиске город на Москву – обновляем заголовок "Погода в Москве".

### Опционально можно рассмотреть вариант с добавлением данных о временном отрезке:
- "Погода в Москве на сегодня"
- "Погода в Москве на неделю"
- "Погода в Москве на 10 дней"

**Comment by karambirov** [comment]
Название проекта? Речь шла о названии вкладки в браузере.
Ещё в описании задачи нужно переформулировать первое предложение

**Comment by tirakhimov** [comment]
Исправил
