### ISSUE TITLE
Стилизовать input поиска города

### ISSUE THREAD

**Issue by denkhis** [StayInLight/react-weather-app#44]
1. Добавить псевдокласс `hover`, чтобы при наведении на `input` он выделялся
2. Добавить псевдоклласс `focus`, чтобы при нажатии на `input` он подчеркивался и пропадал `placeholder`
3. Убрать дефолтный `border` у инпута

**Comment by karambirov** [comment]
@denkhis, задача ещё актуальна после #50?

**Comment by denkhis** [comment]
> @denkhis, задача ещё актуальна после #50?

**Comment by denkhis** [comment]
Задача не актуальна, после issue #50
