### ISSUE TITLE
Использовать Redux в качестве менеджера состояния

### ISSUE THREAD

**Issue by tirakhimov** [StayInLight/react-weather-app#48]
### Что нужно сделать

- Добавить Redux в проект
- Использовать Redux для менеджмента состояния в приложении

**Comment by Destroyou** [comment]
Крайне не рекомендую использовать Redux

**Comment by tirakhimov** [comment]
> Крайне не рекомендую использовать Redux

Почему?

**Comment by Destroyou** [comment]
Банальная проблема: он очень и очень многословный. И оно того не стоит
Т.к. планируете мигрировать на тайпскрипт, то рекомендую взять mobx. Хотя на нем в 5 версии можно уже и вовсе без декораторов писать

**Comment by tirakhimov** [comment]
@Destroyou 

Если вы хорошо разбираетесь в экосистеме React и могли бы помочь нам с проектом, добавьтесь пожалуйста в группу телеграм, где мы обсуждаем проект. 

https://t.me/joinchat/Cie5-xkLa7l2WwTaA5xeWA
